CHROMIUM: drm: fix drm-get-put.cocci warnings
Use drm_*_get() and drm_*_put() helpers instead of drm_*_reference() and
drm_*_unreference() helpers.

Else we get below errors:
drivers/gpu/drm/evdi/evdi_modeset.c:124:2: error: implicit declaration of function 'drm_gem_object_unreference_unlocked' [-Werror,-Wimplicit-function-declaration]
        drm_gem_object_unreference_unlocked(obj);
        ^

Generated by: scripts/coccinelle/api/drm-get-put.cocci

Change-Id: Ida7da9070b54771ab8f183b9644e5726f8cd3f0e
Signed-off-by: Sai Prakash Ranjan <saiprakash.ranjan@codeaurora.org>