Revert "ANDROID: fs: fuse: fix filler function type mismatch"
This reverts commit b8681ba3e414f4025b264bc0e36572d7dd215e55.

Fixes the following build error:

error: incompatible pointer types passing 'int (struct file *, struct page *)' to parameter of type 'filler_t *' (aka 'int (*)(void *, struct page *)') [-Werror,-Wincompatible-pointer-types]
        err = read_cache_pages(mapping, pages, fuse_readpages_fill, &data);
                                               ^~~~~~~~~~~~~~~~~~~