CHROMIUM: Revert "thermal: remove unused function parameter"
This reverts commit 5be52fccaf3d218b278320b0d183aa36aab48add.

Fixes below build error:

drivers/thermal/thermal_core.c: In function ‘handle_non_critical_trips’:
drivers/thermal/thermal_core.c:361:10: error: ‘trip_type’ undeclared (first use in this function)
          trip_type, NULL);
          ^~~~~~~~~