ANDROID: CHROMIUM: Revert "timekeeping: remove timespec_add/timespec_del"
This reverts commit 437e78d3fd6d35e6d56230962e6d03bb5dcda7f6.

This fixes build error seen below with android patch on chromium:

kernel/power/wakeup_reason.c: In function ‘last_suspend_time_show’:
kernel/power/wakeup_reason.c:87:15: error: implicit declaration of function ‘timespec_sub’ [-Werror=implicit-function-declaration]
  sleep_time = timespec_sub(total_time, suspend_resume_time);
               ^~~~~~~~~~~~
kernel/power/wakeup_reason.c:87:13: error: incompatible types when assigning to type ‘struct timespec’ from type ‘int’
  sleep_time = timespec_sub(total_time, suspend_resume_time);
             ^