Revert "y2038: remove unused time interfaces"
This reverts commit 976516404ff3fab2a8caa8bd6f5efc1437fed0b8.

Fixes below build error:

drivers/iio/common/cros_ec_sensors/cros_ec_sensors_ring.c: In function ‘cros_ec_get_time_ns’:
drivers/iio/common/cros_ec_sensors/cros_ec_sensors_ring.c:100:2: error: implicit declaration of function ‘get_monotonic_boottime’ [-Werror=implicit-function-declaration]
  get_monotonic_boottime(&ts);
  ^~~~~~~~~~~~~~~~~~~~~~