Revert "SELinux: Remove unused selinux_is_enabled"
This reverts commit 3d252529480c68bfd6a6774652df7c8968b28e41.

Fixes below build error:

fs/ecryptfs/kthread.c:14:27: fatal error: linux/selinux.h: No such file or directory
 #include <linux/selinux.h>
                           ^