ANDROID: CHROMIUM: Revert "timekeeping: remove obsolete time accessors"
This reverts commit e4b92b108c6cd6b311e4b6e85d6a87a34599a6e3.

Fixes below build error:

fs/configfs/inode.c: In function ‘configfs_alloc_iattr’:
fs/configfs/inode.c:61:42: error: implicit declaration of function ‘current_kernel_time64’ [-Werror=implicit-function-declaration]
    sd_iattr->ia_ctime = timespec64_trunc(current_kernel_time64(), s_time_gran);
                                          ^~~~~~~~~~~~~~~~~~~~~
fs/configfs/inode.c:61:42: error: incompatible type for argument 1 of ‘timespec64_trunc’
In file included from ./include/linux/huge_mm.h:8:0,
                 from ./include/linux/mm.h:590,
                 from ./include/linux/pagemap.h:8,
                 from fs/configfs/inode.c:18:
./include/linux/fs.h:1553:26: note: expected ‘struct timespec64’ but argument is of type ‘int’
 extern struct timespec64 timespec64_trunc(struct timespec64 t, unsigned gran);
                          ^~~~~~~~~~~~~~~~