CHROMIUM: drivers: Create pkglist for configuration
This commit imports pkglist and fixes compilation errors
on 4.14:

* Import pkglist:
  This moves the configuration for sdcardfs into an
  independent driver, allowing the code to be reused
  for alternate approaches or implementations. It
  also provides a way to swap out the implementation
  if others are desired.

  (cherry picked from commit 12538f8144fbf39e7196f1838a998a937461dcc8)
  Reviewed-on: https://chromium-review.googlesource.com/791973

* Fix-up:
  drivers/pkglist/pkglist.c:169:10-11: WARNING:
	return of 0/1 in function '__is_excluded' with return type bool

  (cherry picked from commit 70545796f3e48abd23e32cb376e932900c08c182)
  Reviewed-on: https://chromium-review.googlesource.com/929010

* Port to 4.4:
  - show() and store() are now part of the configfs_attribute.
  - Generalize function definitions to use config_item.
  - Combine the generation of packages_attr and extension_values_attr

  (cherry picked from commit 3fe75b8caaadd5648e883e13f4dae1b7983c6bb9)
  Reviewed-on: https://chromium-review.googlesource.com/792494

* Port to 4.14:
  - Add zero salt to init_name_hash.
  - config_group->default_groups is now a list, use configfs_add_default_group.
  - Add linux/cred.h for namepsace related functions.

BUG=b:63876697
TEST=compilation, mount esdfs

Change-Id: I466bdb280d5a215a06f699b0c8c1dba0efac94c8
Reviewed-on: https://chromium-review.googlesource.com/963406
Commit-Ready: Sarthak Kukreti <sarthakkukreti@chromium.org>
Tested-by: Sarthak Kukreti <sarthakkukreti@chromium.org>
Reviewed-by: Gwendal Grignou <gwendal@chromium.org>

Conflicts:
	drivers/Kconfig
	drivers/Makefile

[rebase419(groeck): Context conflicts]
Signed-off-by: Guenter Roeck <groeck@chromium.org>